### ISSUE TITLE
Version Catalogs not triggering any changes detected

### ISSUE THREAD

**Issue by AlexanderMann** [Crimix/ChangedProjectsTaskPlugin#6]
# Motivation

Hello!

We're happily leveraging your work for our own workflows here at Apollo GraphQL. My colleague [@rwilcox](https://github.com/rwilcox) was actually the one who first implemented the use of this for us and it's worked great.

A bug (maybe?) that we've run into is that we're not seeing any changes detected when our [Version Catalog](https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog) changes, but none of our modules do. ie, for instances where we're trying to bump a 3rd party library to a latest version.

Curious if you've run into this/might know what's going on here and even if this is something that this plugin _can_ support?

**Comment by Crimix** [comment]
Hi, happy to hear it has been working great for you so far.

I am not completely sure what your setup is, I guess the version catalogues are defined in some file in the root of your project? 

I have personally defined it such that changes to let's say the Gradle settings / Gradle build file file in the root triggers a full build as it is possible for it to affect all modules. How have you configured the plugin?

**Comment by AlexanderMann** [comment]
Yeah, so our build cache normally invalidates when the version catalog has changes in it, but ideally we wouldn't see our _entire_ project get invalidated, but rather just the specific dependencies which have impacted changes.

In looking over the logic herein though, it's looking like that's not really how this _could_ work though yeah? ie, changes are detected as entire files yeah? There's no way for a single file to have various lines change and that trickle out to projects which are impacted?

For instance, our versions catalog looks something like the following:

### version.catalog.toml

```toml
[versions]
apollo = "3.2.0"
apollo_federation = "0.9.0"

[libraries]
apollo-adapters = { module = "com.apollographql.apollo3:apollo-adapters", version.ref = "apollo" }
apollo-federation = { module = "com.apollographql.federation:federation-graphql-java-support", version.ref = "apollo_federation" }
```

Let's say we have two modules, `foo` and `bar` which look like the following:

### foo

```kts
plugins {
	kotlinJVM
	junit
}

dependencies {
	api(libs.apollo.federation)
}
```

### bar

```kts
plugins {
	kotlinJVM
	junit
}

dependencies {
	implementation(libs.apollo.adapters)
}
```

Ideally, if we were to bump `apollo_federation` to `0.9.1` in `version.catalog.toml`, we'd see `foo` have changes, but not `bar`
